builds:
  - binary: gocli2
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

brews:
  -
    name: gocli2
    homepage: https://github.com/jr-frazier/go-cli2
    tap:
      owner: jr-frazier
      name: homebrew-jr-frazier
    commit_author:
      name: jrFrazier
      email: jrfrazier.dev@gmail.com
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - maintainer: "JR Frazier"
    package_name: "gocli2"
    formats:
      - deb
      - rpm
      - apk